services:
  db:
    image: postgres:16
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: reddit
    ports:
      - "5555:5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db: