// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CommentInput struct {
	PostID   string  `json:"postId"`
	Content  string  `json:"content"`
	ParentID *string `json:"parentId,omitempty"`
}

type Mutation struct {
}

type PaginationInput struct {
	Limit int32 `json:"limit"`
	Page  int32 `json:"page"`
}

type Query struct {
}

type Subscription struct {
}
