// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Comment struct {
	ID        string     `json:"id"`
	Content   string     `json:"content"`
	CreatedAt time.Time  `json:"createdAt"`
	UpdatedAt time.Time  `json:"updatedAt"`
	User      *User      `json:"user"`
	Parent    *Comment   `json:"parent,omitempty"`
	Replies   []*Comment `json:"replies"`
}

type CommentConn struct {
	TotalCount int32      `json:"totalCount"`
	Comments   []*Comment `json:"comments"`
}

type Mutation struct {
}

type PaginationInput struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type Post struct {
	ID              string       `json:"id"`
	Title           string       `json:"title"`
	Description     string       `json:"description"`
	CreatedAt       time.Time    `json:"createdAt"`
	UpdatedAt       time.Time    `json:"updatedAt"`
	CommentsEnabled bool         `json:"commentsEnabled"`
	User            *User        `json:"user"`
	Comments        *CommentConn `json:"comments"`
}

type Query struct {
}

type Subscription struct {
}

type User struct {
	ID        string    `json:"id"`
	Username  string    `json:"username"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}
